name: money2_improver
description: This is just a 'fix' package for Money2
version: 1.2.0
repository: https://github.com/broxus/money2_improver

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  money2: ^3.3.0
