name: money2_improver
description: This is just a 'fix' package for Money2
version: 1.3.4
repository: https://github.com/broxus/money2_improver

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
dependencies:
  money2: ^5.0.0
